// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE38kVn_o1ksIPlkKMGLOQm_rjr2z9eio',
    appId: '1:21159580239:web:d8792798f5d58f751f503a',
    messagingSenderId: '21159580239',
    projectId: 'balance-meal-bd7da',
    authDomain: 'balance-meal-bd7da.firebaseapp.com',
    storageBucket: 'balance-meal-bd7da.firebasestorage.app',
    measurementId: 'G-449P869ZSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqBjY5kJTSiL3Plx0v9qawP3APIyuNtY',
    appId: '1:21159580239:android:0aa2696119c3cf921f503a',
    messagingSenderId: '21159580239',
    projectId: 'balance-meal-bd7da',
    storageBucket: 'balance-meal-bd7da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTdiSqvKK2IlklotP4G4DlTu22Ek9BiY',
    appId: '1:21159580239:ios:39822ce659310f1e1f503a',
    messagingSenderId: '21159580239',
    projectId: 'balance-meal-bd7da',
    storageBucket: 'balance-meal-bd7da.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOTdiSqvKK2IlklotP4G4DlTu22Ek9BiY',
    appId: '1:21159580239:ios:39822ce659310f1e1f503a',
    messagingSenderId: '21159580239',
    projectId: 'balance-meal-bd7da',
    storageBucket: 'balance-meal-bd7da.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE38kVn_o1ksIPlkKMGLOQm_rjr2z9eio',
    appId: '1:21159580239:web:4be44b0c1099f53c1f503a',
    messagingSenderId: '21159580239',
    projectId: 'balance-meal-bd7da',
    authDomain: 'balance-meal-bd7da.firebaseapp.com',
    storageBucket: 'balance-meal-bd7da.firebasestorage.app',
    measurementId: 'G-Y36YRN0HZJ',
  );
}
